### ISSUE TITLE
`database_z1/0' is not running after update when deploying Diego

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry-incubator/bosh-azure-cpi-release#85]
```
Acting as user 'admin' on deployment 'cf-diego' on 'bosh'
Getting deployment properties from director...

Deploying
---------

Director task 74
  Started unknown
  Started unknown > Binding deployment. Done (00:00:00)

  Started preparing deployment
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:00)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started preparing dns > Binding DNS. Done (00:00:00)

  Started preparing configuration > Binding configuration. Done (00:00:01)

  Started updating job database_z1 > database_z1/0 (canary). Failed: `database_z1/0' is not running after update (00:02:55)

Error 400007: `database_z1/0' is not running after update

Task 74 error

For a more detailed error report, run: bosh task 74 --debug
```

We ssh into `database_z1/0` and find `etcd` is not running because `etcdmain: listen tcp 0.0.0.0:7001: bind: address already in use`.

```
root@39d8e04e-5544-4a40-88b0-3498590eb581:/var/vcap/sys/log/etcd# monit summary
The Monit daemon 5.2.5 uptime: 28m

Process 'etcd'                      not monitored
Process 'bbs'                       running
Process 'consul_agent'              running
Process 'metron_agent'              running
System 'system_localhost'           running
```

This issue is about diego release itself. A similar one is tracked here.
https://github.com/cloudfoundry-incubator/diego-release/issues/119

**Comment by svrc-pivotal** [comment]
This is a known bug with the database_z1 job  that's been fixed but not in a release yet- https://www.pivotaltracker.com/n/projects/1488988/stories/110687048  

Workaround is to manually restart etcd once the consul job is up.

To do this, break out of the deploy while it's updating database_z1, then  `bosh ssh database_z1`  and `sudo su; monit quit etcd ; monit quit bbs ;  killall -9 etcd ; monit start all`

**Comment by bingosummer** [comment]
Thank you @svrc-pivotal .
Will close it after the fix is released.

**Comment by svrc-pivotal** [comment]
FYI, the fix is done but the problem is still occurring.  I've filed a ticket with Pivotal support

**Comment by svrc-pivotal** [comment]
This has been fixed in PCF 1.6.17,  Diego releases 0.1446.3+ and 0.1452.0+ , etcd release 27 +

**Comment by AbelHu** [comment]
The doc for Diego has been updated. Just close it.
